
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /single-pod/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: single-pod-pod-service
            port:
              number: 8080 
    
      - path: /two-pod-same-node/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: two-pod-same-node-nginx-service
            port:
              number: 80 
    
      - path: /hpa/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: hpa-service
            port:
              number: 8080 
    
      - path: /vpa/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: vpa-service
            port:
              number: 8080 
    
      - path: /two-container/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-loadbalancer-service-two-container
            port:
              number: 80 
    
      - path: /two-pod-diff-node/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: two-pod-diff-node-loadbalancer-service
            port:
              number: 80 
    
