
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-testing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-testing-app
  template:
    metadata:
      labels:
        app: map-testing-app 
    spec:
      containers:
      - name: map-testing-app 
        image: arijitsaha2002/flask_app:0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000 
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: map-testing-service
  labels:
    app: map-testing-app
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000 
  selector:
    app: map-testing-app 
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment-map-testing
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: map-testing-app
 minReplicas: 1
 maxReplicas: 10
 metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map-testing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /flask/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: map-testing-service
            port:
              number: 8080 

