
apiVersion: apps/v1
kind: Deployment
metadata:
  name: -deployment-app 
spec:
  selector:
    matchLabels:
      app: -app
  replicas: 2
  template:
    metadata:
      labels:
        app: -app
    spec:
      containers:
        - name: -cotainer
          image: 
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
            limits:
              cpu: 50m
          ports:
            - containerPort:  

---
apiVersion: v1
kind: Service
metadata:
  name: -vpa-service
spec:
  selector:
    app: -app 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 
      targetPort:  

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-development-
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: -deployment-app
  resourcePolicy:
    containerPolicies:
      - containerName: -cotainer
        minAllowed:
          cpu: 10m
          memory: 10Mi
        maxAllowed:
          cpu: 50m
          memory: 50Mi
        controlledResources: ["cpu", "memory"]

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: -vpa-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: //(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: -vpa-service
            port:
              number: 8080 

