apiVersion: v1
kind: Pod
metadata:
  name: flask-app-single-pod
  labels:
    app: flask-app-single-pod 
spec:
  containers:
  - name: flask-app-single-container
    image: arijitsaha2002/flask_app:0.2
    ports:
    - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-single-pod-service
spec:
  selector:
    app: flask-app-single-pod  
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 5000  
  type: LoadBalancer


