
apiVersion: v1
kind: Pod
metadata:
  name: aryan-tc-app-1
  labels:
    app: aryan-tc-app-1
spec:
  containers:
  - name: aryan-tc-container-1
    image: arijitsaha2002/flask_app:0.2
    ports:
    - containerPort: 5000 
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
  - name: aryan-tc-container-2
    image: arijitsaha2002/flask_app:0.4 
    ports:
    - containerPort: 5001
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer-aryan-tc
  labels:
    app: nginx-loadbalancer-aryan-tc
spec:
  containers:
  - name: nginx-loadbalancer-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service-aryan-tc
spec:
  selector:
    app: nginx-loadbalancer-aryan-tc
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80  
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /aryan-tc/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-loadbalancer-service-aryan-tc
            port:
              number: 80 

