
apiVersion: v1
kind: Pod
metadata:
  name: aryan-sp-pod
  labels:
    app: aryan-sp-pod 
spec:
  containers:
  - name: aryan-sp-container
    image: arijitsaha2002/flask_app:0.2 
    ports:
    - containerPort: 5000 
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: aryan-sp-pod-service
spec:
  selector:
    app: aryan-sp-pod  
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 5000  
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /aryan-sp/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: aryan-sp-pod-service
            port:
              number: 8080 

