
apiVersion: v1
kind: Pod
metadata:
  name: arijit-two-container-app-1
  labels:
    app: arijit-two-container-app-1
spec:
  containers:
  - name: arijit-two-container-container-1
    image: arijit-two-container-1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000 
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
  - name: arijit-two-container-container-2
    image: arijit-two-container-2 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5001
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer-arijit-two-container
  labels:
    app: nginx-loadbalancer-arijit-two-container
spec:
  containers:
  - name: nginx-loadbalancer-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service-arijit-two-container
spec:
  selector:
    app: nginx-loadbalancer-arijit-two-container
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80  
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /two-container/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-loadbalancer-service-arijit-two-container
            port:
              number: 80 

