
apiVersion: v1
kind: Pod
metadata:
  name: two-cont-app-1
  labels:
    app: two-cont-app-1
spec:
  containers:
  - name: two-cont-container-1
    image: arijitsaha2002/flask_app:0.2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000 
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
  - name: two-cont-container-2
    image: arijitsaha2002/flask_app:0.4 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5001
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer-two-cont
  labels:
    app: nginx-loadbalancer-two-cont
spec:
  containers:
  - name: nginx-loadbalancer-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service-two-cont
spec:
  selector:
    app: nginx-loadbalancer-two-cont
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80  
  type: LoadBalancer


