
apiVersion: v1
kind: Pod
metadata:
  name: two-container-2-app-1
  labels:
    app: two-container-2-app-1
spec:
  containers:
  - name: two-container-2-container-1
    image: two-container-2-1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000 
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
  - name: two-container-2-container-2
    image: two-container-2-2 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5001
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer-two-container-2
  labels:
    app: nginx-loadbalancer-two-container-2
spec:
  containers:
  - name: nginx-loadbalancer-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service-two-container-2
spec:
  selector:
    app: nginx-loadbalancer-two-container-2
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80  
  type: LoadBalancer


