
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arijit-hpa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arijit-hpa-app
  template:
    metadata:
      labels:
        app: arijit-hpa-app 
    spec:
      containers:
      - name: arijit-hpa-app 
        image: arijit-hpa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000 
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: arijit-hpa-service
  labels:
    app: arijit-hpa-app
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000 
  selector:
    app: arijit-hpa-app 
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment-arijit-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: arijit-hpa-app
 minReplicas: 1
 maxReplicas: 10
 metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /hpa/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: arijit-hpa-service
            port:
              number: 8080 

